[build.environment]
  NPM_FLAGS = "--version"
  NETLIFY_USE_PNPM = "true"
[build]
  command = "pnpm build"
  publish = "dist"
  environment = { NODE_VERSION = "22.14.0" }
[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"