[build.environment]
  NODE_VERSION = "18.17.1"
  NPM_FLAGS = "--version"
  NETLIFY_USE_PNPM = "true"

[build]
  command = "pnpm build"
  publish = "dist"
[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"